stages:        
- stage: Destroy_Stage
  variables:
    - group: pipelines-aks-vars
  displayName: Infrastructure Destruction
  jobs:  
  - job: Destroy
    displayName: Destroy of Resources in the Real Environment
    steps:
      - task: TerraformCLI@0
        displayName: Terraform Init
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/03-Create-AKS-Cluster/stacks/tftec'
          commandOptions: '-reconfigure'
          backendType: 'azurerm'
          backendServiceArm: 'pipelines-aks'
          backendAzureRmResourceGroupName: '$(TF-BACKEND-RESOURCE-GROUP)'
          backendAzureRmStorageAccountName: '$(TF-BACKEND-STORAGE-ACCOUNT)'
          backendAzureRmContainerName: '$(TF-BACKEND-CONTAINER)'
          backendAzureRmKey: '$(TF-BACKEND-KEY)'
          allowTelemetryCollection: true

      - task: TerraformCLI@0
        displayName: Select Workspace
        inputs:
          command: workspace
          workingDirectory: '$(System.DefaultWorkingDirectory)/03-Create-AKS-Cluster/stacks/tftec'
          workspaceSubCommand: select
          workspaceName: live

      - task: TerraformCLI@0
        displayName: Terraform Plan (Destroy)
        inputs:
          command: 'plan'
          environmentServiceName: 'pipelines-aks'
          workingDirectory: '$(System.DefaultWorkingDirectory)/03-Create-AKS-Cluster/stacks/tftec'
          commandOptions: '-destroy --var-file="../env/aovivo-sp-24/aovivosp24.tfvars"'
          allowTelemetryCollection: true

      - task: TerraformCLI@0
        displayName: Terraform Apply (Destroy)
        inputs:
          command: 'apply'
          environmentServiceName: 'pipelines-aks'
          workingDirectory: '$(System.DefaultWorkingDirectory)/03-Create-AKS-Cluster/stacks/tftec'
          commandOptions: '-destroy -auto-approve --var-file="../env/aovivo-sp-24/aovivosp24.tfvars"'
          allowTelemetryCollection: true
